name: Local Mode load test

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  local-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js (optional, only if required)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run test-load script for local workflow
        working-directory: signify-ts-test/
        env:
          BANK_COUNT: ${{ vars.BANK_COUNT }}
        run: |
          chmod +x test-load.sh
          ./test-load.sh --mode local --bank-count $BANK_COUNT
